export const INITIAL_FORM_VALUES = {
  bf_name: 'NATHMAL SHARMA',
  bf_gstin: '18AIKPS1729A6Z6',
  bf_street: 'Pamohi Road, Maghawa Para, Gorchuk',
  bf_city: 'Guwahati',
  bf_state: 'Assam',
  bf_zip: 781035,
  bt_name: '',
  bt_gstin: '',
  bt_street: '',
  bt_city: '',
  bt_state: '',
  bt_zip: '',
  s_street: '',
  s_city: '',
  s_state: '',
  s_zip: '',
  rent_type: 'variable',
  area: 0.0,
  unit: 'sq. ft.',
  invoice_no: '',
  invoice_date: '',
  pan: 'AIKPS1729A',
  sac: 997212,
  p_head: 'Renting of immovable property Service',
  p_content: '',
  p_note: '',
  taxable_amount: 0.0,
  per_rate: 0.0,
  isSubmitting: false,
  submitted: false,
  isFormValid: false,
  taxed_amount: 0.0,
  tax_amount: 0.0,
  isIGST: false,
  amount_in_words: 'zero',
};

export const INITIAL_TEST_FORM_VALUES = {
  bf_name: 'NATHMAL SHARMA',
  bf_gstin: '18AIKPS1729A6Z6',
  bf_street: 'Pamohi Road, Maghawa Para, Gorchuk',
  bf_city: 'Guwahati',
  bf_state: 'Assam',
  bf_zip: 781035,
  bt_name: 'NATHMAL SHARMA',
  bt_gstin: '18AIKPS1729A6Z6',
  bt_street: 'Pamohi Road, Maghawa Para, Gorchuk',
  bt_city: 'Guwahati',
  bt_state: 'Assam',
  bt_zip: 781035,
  s_street: 'Pamohi Road, Maghawa Para, Gorchuk',
  s_city: 'Guwahati',
  s_state: 'Assam',
  s_zip: 781035,
  rent_type: 'variable',
  area: 0.0,
  unit: 'sq. ft.',
  pan: 'AIKPS1729A',
  sac: 997212,
  p_head: 'Renting of immovable property Service',
  p_content: '//write here',
  p_note: '//write note here',
  taxable_amount: 0.0,
  per_rate: 0.0,
  isSubmitting: false,
  submitted: false,
  isFormValid: false,
  taxed_amount: 0.0,
  tax_amount: 0.0,
  isIGST: false,
};
