import moment from 'moment';
const dateFormat = 'DD/MM/YYYY';

export const INITIAL_FORM_VALUES = {
  bf_name: 'NATHMAL SHARMA',
  bf_gstin: '18AIKPS1729A6Z6',
  bf_street: 'Pamohi Road, Maghawa Para, Gorchuk',
  bf_city: 'Guwahati',
  bf_state: 'Assam',
  bf_zip: 781035,
  bt_name: '',
  bt_gstin: '',
  bt_street: '',
  bt_city: '',
  bt_state: '',
  bt_zip: '',
  s_street: '',
  s_city: '',
  s_state: '',
  s_zip: '',
  rent_type: 'variable',
  invoice_no: '0001',
  invoice_date: moment(moment().toDate(), dateFormat),
  area: 0.0,
  unit: 'sq. ft.',
  pan: 'AIKPS1729A',
  sac: 997212,
  p_head: 'Renting of immovable property Service',
  p_content: `Towards the Rent on Immovable Property for the period of MAY 2021 in Respect of Warehouse RCC Building Ground ,1st & 2nd Floor, Situated at PAMOHI ROAD, MAGHAWA PARA, GORCHUK, GUWAHATI - 781 035 (ASSAM)`,
  p_note: '',
  taxable_amount: 0.0,
  per_rate: 0.0,
  taxed_amount: 0.0,
  tax_amount: 0.0,
  isSameState: false,
  amount_in_words: 'zero',
};

export const INITIAL_TEST_FORM_VALUES = {
  bf_name: 'NATHMAL SHARMA',
  bf_gstin: '18AIKPS1729A6Z6',
  bf_street: 'Pamohi Road, Maghawa Para, Gorchuk',
  bf_city: 'Guwahati',
  bf_state: 'Assam',
  bf_zip: 781035,
  bt_name: 'PAWAN SHARMA',
  bt_gstin: '18AIKPS1729A6Z6',
  bt_street: 'New Pamohi Road, Maghawa Para, Gorchuk',
  bt_city: 'Guwahati',
  bt_state: 'Assam',
  bt_zip: 781035,
  s_street: 'Pamohi Road, Maghawa Para, Gorchuk',
  s_city: 'Guwahati',
  s_state: 'Assam',
  s_zip: 781035,
  rent_type: 'variable',
  invoice_no: '0001',
  invoice_date: moment(moment().toDate(), dateFormat).toString(),
  area: 0.0,
  unit: 'sq. ft.',
  pan: 'AIKPS1729A',
  sac: 997212,
  p_head: 'Renting of Immovable Property Service',
  p_content: `Towards the Rent on Immovable Property for the period of MAY 2021 in Respect of Warehouse RCC Building Ground ,1st & 2nd Floor, Situated at PAMOHI ROAD, MAGHAWA PARA, GORCHUK, GUWAHATI - 781 035 (ASSAM)`,
  p_note: '//write note here',
  taxable_amount: 0.0,
  per_rate: 0.0,
  taxed_amount: 0.0,
  tax_amount: 0.0,
  isSameState: false,
  amount_in_words: 'zero',
};
